name: my-environment
channels:
  - conda-forge
dependencies:
  - python==3.6.*
  - numpy==1.15.2
  - pandas==0.24.2
  - wordcloud==1.5.0
  - scikit-learn==0.20.3
  - pip
  - pip:
    - matplotlib==2.2.4
